import type { Recipe } from '../../types.js'

export const demoTomatoEggRecipe: Recipe = {
  id: 'demo-tomato-egg',
  title: '番茄炒蛋',
  subtitle: '复赛演示固定菜谱',
  scene: '新手第一道家常菜',
  difficulty: '零失败' as Recipe['difficulty'],
  duration: 15,
  servings: 2,
  highlight: '先把鸡蛋炒嫩盛出，再用番茄炒出汁，最后合炒调味。',
  riskNote: '最容易翻车的是鸡蛋炒老、番茄没出汁、盐一次加太多。',
  description: '一份适合演示“一步一屏跟做”的番茄炒蛋结构化菜谱。',
  tags: ['演示视频', '家常菜', '新手友好'],
  searchTokens: ['番茄炒蛋', '西红柿炒鸡蛋', '鸡蛋', '番茄'],
  tools: ['炒锅', '锅铲', '碗', '菜刀', '砧板'],
  ingredients: [
    { name: '番茄', amount: '2 个，约 300 克' },
    { name: '鸡蛋', amount: '3 个' },
    { name: '葱花', amount: '1 小把' },
    { name: '盐', amount: '约 2 克，分两次加' },
    { name: '白糖', amount: '约 3 克，可选' },
    { name: '食用油', amount: '约 20 毫升' },
  ],
  substitutions: [
    {
      ingredient: '白糖',
      replacement: '不放或少量番茄酱',
      tip: '番茄足够成熟时可以不放糖；偏酸时再少量补。',
    },
  ],
  rescueTips: [
    {
      issue: '做糊了怎么办？',
      keywords: ['糊', '焦', '黑'],
      answer: '先立刻关小火，把没有糊味的部分拨到锅边或盛出；锅底焦黑的不要刮进菜里。再用一点热水把番茄汁补回来，最后重新调味。',
    },
    {
      issue: '太咸了怎么办？',
      keywords: ['咸', '盐多'],
      answer: '先不要再加盐。可以补半个番茄或一点热水，把汤汁拉开；如果还有鸡蛋液，也可以再炒一点鸡蛋拌进去稀释咸味。',
    },
  ],
  steps: [
    {
      title: '处理番茄和蛋液',
      instruction: '番茄切小块，鸡蛋打散到看不见明显蛋清。',
      detail: '番茄块切小一点更容易出汁。蛋液里可以加一小撮盐，搅到颜色均匀。',
      durationMinutes: 3,
      sensoryCue: '番茄块大小接近一口，蛋液颜色均匀、没有透明蛋清。',
      checkpoints: ['番茄蒂去掉', '蛋液完全打散', '调料先放在手边'],
      commonMistakes: ['番茄切太大导致后面不出汁', '蛋液没打散，炒出来有白色硬块'],
      demoFrames: ['番茄切块', '鸡蛋打散', '调料备好'],
      voiceover: '先切番茄，再打蛋液，把盐和糖放在手边。',
    },
    {
      title: '先炒鸡蛋',
      instruction: '锅热后倒油，倒入蛋液，边缘凝固后轻轻推开，八成熟就盛出。',
      detail: '鸡蛋不要炒到全干。看到大部分凝固、还有一点嫩的时候就离锅。',
      durationMinutes: 2,
      sensoryCue: '鸡蛋蓬松成块，表面还有一点湿润光泽。',
      checkpoints: ['油温够热再倒蛋', '不要反复压碎鸡蛋', '八成熟先盛出'],
      commonMistakes: ['火太小导致鸡蛋吸油', '炒太久变干变硬'],
      demoFrames: ['热锅倒油', '蛋液下锅', '八成熟盛出'],
      voiceover: '鸡蛋先炒嫩，八成熟就盛出来，后面还会回锅。',
    },
    {
      title: '炒番茄出汁',
      instruction: '锅里留底油，下番茄块，中火翻炒到变软出汁。',
      detail: '可以加一小撮盐帮助番茄出汁。如果番茄偏硬，加一勺热水再炒。',
      durationMinutes: 4,
      sensoryCue: '番茄边缘变软，锅底出现红色汤汁。',
      checkpoints: ['番茄明显变软', '锅底有红汁', '没有焦黑粘锅'],
      commonMistakes: ['番茄刚下锅就急着倒鸡蛋', '锅太干还继续大火炒'],
      demoFrames: ['番茄下锅', '中火翻炒', '炒出红汁'],
      voiceover: '这一步的目标是让番茄出汁，不要急着放鸡蛋。',
    },
    {
      title: '鸡蛋回锅合炒',
      instruction: '把鸡蛋倒回锅里，和番茄汁轻轻翻匀。',
      detail: '动作轻一点，保留鸡蛋块。让鸡蛋吸到番茄汁就可以。',
      durationMinutes: 2,
      sensoryCue: '鸡蛋表面裹上红色番茄汁，但仍然成块。',
      checkpoints: ['鸡蛋和番茄汁混合均匀', '鸡蛋没有被铲得太碎', '锅底还有少量汤汁'],
      commonMistakes: ['用力翻炒把鸡蛋弄碎', '收得太干导致口感发柴'],
      demoFrames: ['鸡蛋回锅', '轻轻翻匀', '裹上番茄汁'],
      voiceover: '鸡蛋回锅后轻轻翻匀，让它吸到番茄汁。',
    },
    {
      title: '调味出锅',
      instruction: '尝一下味道，少量补盐或糖，撒葱花后出锅。',
      detail: '最后调味要少量多次。番茄酸就加一点糖，味道淡再补一点盐。',
      durationMinutes: 2,
      sensoryCue: '味道酸甜咸平衡，汤汁能薄薄挂在鸡蛋上。',
      checkpoints: ['先尝再补盐', '汤汁不要完全收干', '葱花最后再放'],
      commonMistakes: ['盐一次加太多', '出锅前继续久炒导致鸡蛋变老'],
      demoFrames: ['尝味道', '撒葱花', '装盘出锅'],
      voiceover: '最后先尝味道，少量补盐或糖，撒葱花就出锅。',
    },
  ],
  palette: {
    start: '#fed7aa',
    end: '#fb923c',
  },
  visibility: 'official',
  sourceType: 'official',
}

export const demoQuickQuestions = [
  '这一步做到什么程度算好？',
  '为什么要这样做？',
  '做糊了怎么办？',
  '太咸了怎么办？',
]
